# Generated by Django 4.0.3 on 2022-08-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article200',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='ArtNo')),
                ('gen_art_no', models.IntegerField(blank=True, null=True, verbose_name='GenArtNo')),
                ('gtin', models.IntegerField(blank=True, null=True, verbose_name='GTIN')),
                ('quant_unit', models.IntegerField(blank=True, null=True, verbose_name='QuantUnit')),
                ('quant_per_unit', models.IntegerField(blank=True, null=True, verbose_name='QuantPerUnit')),
                ('art_stat', models.IntegerField(blank=True, null=True, verbose_name='ArtStat')),
                ('status_dat', models.IntegerField(blank=True, null=True, verbose_name='StatusDat')),
            ],
            options={
                'verbose_name': 'Артикул',
                'verbose_name_plural': 'Артикулы',
            },
        ),
        migrations.CreateModel(
            name='Country202',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='CountryCode')),
                ('country_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='CountryName')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'default_related_name': 'country',
            },
        ),
        migrations.CreateModel(
            name='CritVal210',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crit_no', models.IntegerField(blank=True, null=True, verbose_name='CritNo')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Список критерий',
                'verbose_name_plural': 'Список критерий',
            },
        ),
        migrations.CreateModel(
            name='Doc231and232',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.IntegerField(blank=True, null=True, verbose_name='DocNo')),
                ('doc_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='DocName')),
                ('lang_no', models.IntegerField(blank=True, null=True, verbose_name='LangNo')),
                ('doc_type', models.IntegerField(blank=True, null=True, verbose_name='DocContentType')),
                ('doc_term_no', models.IntegerField(blank=True, null=True, verbose_name='DocTermNorm')),
                ('doc_type_one', models.IntegerField(blank=True, null=True, verbose_name='DocTermNorm')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Manufacture203',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_no', models.IntegerField(blank=True, null=True, verbose_name='ManNo')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ShortName')),
                ('term_plain', models.CharField(blank=True, max_length=255, null=True, verbose_name='TermPlain')),
            ],
            options={
                'verbose_name': 'Производитель авто',
                'verbose_name_plural': 'Производители авто',
            },
        ),
        migrations.CreateModel(
            name='Supers204',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supers_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='SupersNo')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers200',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('brand_no', models.IntegerField(blank=True, null=True, verbose_name='BrandNo')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('street_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street2')),
                ('country_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='CountryCode')),
                ('post_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='PostCode')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('web_site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Web')),
                ('adr_type', models.IntegerField(blank=True, null=True, verbose_name='AdrType')),
                ('doc_no', models.IntegerField(blank=True, null=True, verbose_name='DocNo')),
                ('doc_type', models.IntegerField(blank=True, null=True, verbose_name='DocType')),
            ],
            options={
                'verbose_name': 'Производитель комплектующей',
                'verbose_name_plural': 'Производители комплектующих',
            },
        ),
        migrations.CreateModel(
            name='Trade207',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='TradeNo')),
                ('first_page', models.IntegerField(blank=True, null=True, verbose_name='FirstPage')),
                ('art_no_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArtNoTrade_207', to='inTecdoc.article200')),
            ],
        ),
        migrations.CreateModel(
            name='Table410',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_art_no', models.IntegerField(blank=True, null=True, verbose_name='GenArtNo')),
                ('lnk_target_type', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType')),
                ('lnk_target_no', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo')),
                ('seq_no', models.IntegerField(blank=True, null=True, verbose_name='SeqNo')),
                ('crit_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='CritNo')),
                ('crit_val', models.CharField(blank=True, max_length=255, null=True, verbose_name='CritVal')),
                ('first_page', models.IntegerField(blank=True, null=True, verbose_name='FirstPage')),
                ('art_no_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArtNoTable410', to='inTecdoc.article200')),
            ],
        ),
        migrations.CreateModel(
            name='Table404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_art_no', models.IntegerField(blank=True, null=True, verbose_name='GenArtNo')),
                ('lnk_target_type', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType')),
                ('lnk_target_no', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo')),
                ('art_no_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArtNoTable404', to='inTecdoc.article200')),
            ],
        ),
        migrations.CreateModel(
            name='Ref203',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='RefNo')),
                ('man_no_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.manufacture203', verbose_name='ManNoName')),
            ],
            options={
                'verbose_name': 'Комплектующая от производителя авто',
                'verbose_name_plural': 'Комплектующие от производителя авто',
            },
        ),
        migrations.CreateModel(
            name='Lnk400',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_art_no', models.IntegerField(blank=True, null=True, verbose_name='GenArtNo')),
                ('lnk_target_type', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType')),
                ('lnk_target_no', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo')),
                ('seq_no', models.IntegerField(blank=True, null=True, verbose_name='SeqNo')),
                ('art_no_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArtNoLnk400', to='inTecdoc.article200')),
            ],
        ),
        migrations.CreateModel(
            name='Crit210',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crit_val', models.CharField(blank=True, max_length=255, null=True, verbose_name='CritVal')),
                ('art_no_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.article200', verbose_name='ArtNo')),
                ('crit_no_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.critval210', verbose_name='CritNo')),
            ],
            options={
                'verbose_name': 'Критерии комплектующего',
                'verbose_name_plural': 'Критерии комплектующих',
            },
        ),
        migrations.AddField(
            model_name='article200',
            name='brand_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_no_article', to='inTecdoc.suppliers200'),
        ),
        migrations.AddField(
            model_name='article200',
            name='country_id',
            field=models.ManyToManyField(blank=True, related_name='CountryArticle_200', to='inTecdoc.country202'),
        ),
        migrations.AddField(
            model_name='article200',
            name='doc_no_id',
            field=models.ManyToManyField(blank=True, related_name='doc_no_article', to='inTecdoc.doc231and232'),
        ),
        migrations.AddField(
            model_name='article200',
            name='ref_no_id',
            field=models.ManyToManyField(blank=True, related_name='ref_no_article', to='inTecdoc.ref203'),
        ),
        migrations.AddField(
            model_name='article200',
            name='supers_id',
            field=models.ManyToManyField(blank=True, related_name='supers_article', to='inTecdoc.supers204'),
        ),
    ]
