# Generated by Django 4.0.3 on 2022-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers200',
            name='data_release',
            field=models.IntegerField(blank=True, null=True, verbose_name='Data Release'),
        ),
    ]
