# Generated by Django 4.0.3 on 2022-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_200',
            name='Country',
            field=models.ManyToManyField(blank=True, null=True, to='inTecdoc.country_202'),
        ),
    ]
