# Generated by Django 4.0.3 on 2022-08-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article200',
            name='supers_id',
            field=models.ManyToManyField(blank=True, related_name='supers_article', to='inTecdoc.supers204'),
        ),
    ]
