# Generated by Django 4.0.3 on 2022-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table001',
            name='BrandName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BrandName'),
        ),
        migrations.AlterField(
            model_name='table001',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table001',
            name='Data',
            field=models.IntegerField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='table001',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table001',
            name='Format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='table001',
            name='Full',
            field=models.IntegerField(blank=True, null=True, verbose_name='Full'),
        ),
        migrations.AlterField(
            model_name='table001',
            name='ManNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='ManNo'),
        ),
        migrations.AlterField(
            model_name='table001',
            name='RefDataVersion',
            field=models.IntegerField(blank=True, null=True, verbose_name='RefDataVersion'),
        ),
        migrations.AlterField(
            model_name='table001',
            name='Release',
            field=models.IntegerField(blank=True, null=True, verbose_name='Release'),
        ),
        migrations.AlterField(
            model_name='table001',
            name='Reserved',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reserved'),
        ),
        migrations.AlterField(
            model_name='table001',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table001',
            name='VersionDate',
            field=models.IntegerField(blank=True, null=True, verbose_name='VersionDate'),
        ),
        migrations.AlterField(
            model_name='table030',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table030',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table030',
            name='LangNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='LangNo'),
        ),
        migrations.AlterField(
            model_name='table030',
            name='Reserved',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reserved'),
        ),
        migrations.AlterField(
            model_name='table030',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table030',
            name='Term',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='table030',
            name='TermNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TermNo'),
        ),
        migrations.AlterField(
            model_name='table035',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table035',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table035',
            name='Fixed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fixed'),
        ),
        migrations.AlterField(
            model_name='table035',
            name='LangNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='LangNo'),
        ),
        migrations.AlterField(
            model_name='table035',
            name='Reserved',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Reserved'),
        ),
        migrations.AlterField(
            model_name='table035',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table035',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table035',
            name='TxtModNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='TxtModNo'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='AdrType',
            field=models.IntegerField(blank=True, null=True, verbose_name='AdrType'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='City1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='City1'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='City2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='City2'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='Email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='Fax',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='POBox',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='POBox'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='Phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='PostCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PostCode'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='PostCodeCus',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PostCodeCus'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='PostCodePOBox',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PostCodePOBox'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='Street1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Street1'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='Street2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Street2'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='Term1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Term1'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='Term2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Term2'),
        ),
        migrations.AlterField(
            model_name='table040',
            name='Web',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Web'),
        ),
        migrations.AlterField(
            model_name='table042',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table042',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table042',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table042',
            name='DocNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocNo'),
        ),
        migrations.AlterField(
            model_name='table042',
            name='DocType',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocType'),
        ),
        migrations.AlterField(
            model_name='table042',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='AdrType',
            field=models.IntegerField(blank=True, null=True, verbose_name='AdrType'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='AdrType1',
            field=models.IntegerField(blank=True, null=True, verbose_name='AdrType1'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='City1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='City1'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='City2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='City2'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='CountryCode1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode1'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='Email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='Fax',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='POBox',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='POBox'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='Phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='PostCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PostCode'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='PostCodeCus',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PostCodeCus'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='PostCodePOBox',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PostCodePOBox'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='Street1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Street1'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='Street2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Street2'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='Term1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Term1'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='Term2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Term2'),
        ),
        migrations.AlterField(
            model_name='table043',
            name='Web',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Web'),
        ),
        migrations.AlterField(
            model_name='table200',
            name='Accessory',
            field=models.IntegerField(blank=True, null=True, verbose_name='Accessory'),
        ),
        migrations.AlterField(
            model_name='table200',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table200',
            name='BatchSize1',
            field=models.IntegerField(blank=True, null=True, verbose_name='BatchSize1'),
        ),
        migrations.AlterField(
            model_name='table200',
            name='BatchSize2',
            field=models.IntegerField(blank=True, null=True, verbose_name='BatchSize2'),
        ),
        migrations.AlterField(
            model_name='table200',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table200',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table200',
            name='MatCert',
            field=models.IntegerField(blank=True, null=True, verbose_name='MatCert'),
        ),
        migrations.AlterField(
            model_name='table200',
            name='Remanufact',
            field=models.IntegerField(blank=True, null=True, verbose_name='Remanufact'),
        ),
        migrations.AlterField(
            model_name='table200',
            name='SelfServ',
            field=models.IntegerField(blank=True, null=True, verbose_name='SelfServ'),
        ),
        migrations.AlterField(
            model_name='table200',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table200',
            name='TermNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TermNo'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='CurCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CurCode'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='Dicount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dicount'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='DiscGroup',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='DiscGroup'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='PrQuantUnit',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PrQuantUnit'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='PrType',
            field=models.IntegerField(blank=True, null=True, verbose_name='PrType'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='PrUnit',
            field=models.IntegerField(blank=True, null=True, verbose_name='PrUnit'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='Price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='Reserved',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Reserved'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='ValidFrom',
            field=models.IntegerField(blank=True, null=True, verbose_name='ValidFrom'),
        ),
        migrations.AlterField(
            model_name='table201',
            name='ValidTo',
            field=models.IntegerField(blank=True, null=True, verbose_name='ValidTo'),
        ),
        migrations.AlterField(
            model_name='table202',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table202',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table202',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table202',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table202',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table202',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table203',
            name='Additive',
            field=models.IntegerField(blank=True, null=True, verbose_name='Additive'),
        ),
        migrations.AlterField(
            model_name='table203',
            name='ArtNO',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNO'),
        ),
        migrations.AlterField(
            model_name='table203',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table203',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table203',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table203',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table203',
            name='ManNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='ManNo'),
        ),
        migrations.AlterField(
            model_name='table203',
            name='RefNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='RefNo'),
        ),
        migrations.AlterField(
            model_name='table203',
            name='ReferenceInfo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ReferenceInfo'),
        ),
        migrations.AlterField(
            model_name='table203',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table203',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table204',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table204',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table204',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table204',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table204',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table204',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table204',
            name='SupersNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='SupersNo'),
        ),
        migrations.AlterField(
            model_name='table204',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table205',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table205',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table205',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table205',
            name='PartGenArtNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='PartGenArtNo'),
        ),
        migrations.AlterField(
            model_name='table205',
            name='PartNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PartNo'),
        ),
        migrations.AlterField(
            model_name='table205',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='table205',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table205',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table206',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table206',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table206',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table206',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table206',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table206',
            name='FirstPage',
            field=models.IntegerField(blank=True, null=True, verbose_name='FirstPage'),
        ),
        migrations.AlterField(
            model_name='table206',
            name='InfType',
            field=models.IntegerField(blank=True, null=True, verbose_name='InfType'),
        ),
        migrations.AlterField(
            model_name='table206',
            name='Reserved',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reserved'),
        ),
        migrations.AlterField(
            model_name='table206',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table206',
            name='TXTModNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='TXTModNo'),
        ),
        migrations.AlterField(
            model_name='table206',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table207',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table207',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table207',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table207',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table207',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table207',
            name='FirstPage',
            field=models.IntegerField(blank=True, null=True, verbose_name='FirstPage'),
        ),
        migrations.AlterField(
            model_name='table207',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table207',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table207',
            name='TradeNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='TradeNo'),
        ),
        migrations.AlterField(
            model_name='table208',
            name='ArtNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table208',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table208',
            name='CritNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='CritNo'),
        ),
        migrations.AlterField(
            model_name='table208',
            name='CritVal',
            field=models.IntegerField(blank=True, null=True, verbose_name='CritVal'),
        ),
        migrations.AlterField(
            model_name='table208',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table208',
            name='Reserved',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reserved'),
        ),
        migrations.AlterField(
            model_name='table208',
            name='Reserved1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reserved1'),
        ),
        migrations.AlterField(
            model_name='table208',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table208',
            name='SeqNo1',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo1'),
        ),
        migrations.AlterField(
            model_name='table208',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table208',
            name='TaleNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TaleNo'),
        ),
        migrations.AlterField(
            model_name='table209',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table209',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table209',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table209',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table209',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table209',
            name='GTIN',
            field=models.IntegerField(blank=True, null=True, verbose_name='GTIN'),
        ),
        migrations.AlterField(
            model_name='table209',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table210',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table210',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table210',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table210',
            name='CritNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='CritNo'),
        ),
        migrations.AlterField(
            model_name='table210',
            name='CritVal',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CritVal'),
        ),
        migrations.AlterField(
            model_name='table210',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table210',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table210',
            name='FirstPage',
            field=models.IntegerField(blank=True, null=True, verbose_name='FirstPage'),
        ),
        migrations.AlterField(
            model_name='table210',
            name='Reserved',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reserved'),
        ),
        migrations.AlterField(
            model_name='table210',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table210',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table211',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table211',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table211',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table211',
            name='GenArtNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='GenArtNo'),
        ),
        migrations.AlterField(
            model_name='table211',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table212',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table212',
            name='ArtStat',
            field=models.IntegerField(blank=True, null=True, verbose_name='ArtStat'),
        ),
        migrations.AlterField(
            model_name='table212',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table212',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table212',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table212',
            name='QuantPerUnit',
            field=models.IntegerField(blank=True, null=True, verbose_name='QuantPerUnit'),
        ),
        migrations.AlterField(
            model_name='table212',
            name='QuantUnit',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='QuantUnit'),
        ),
        migrations.AlterField(
            model_name='table212',
            name='StatusDat',
            field=models.IntegerField(blank=True, null=True, verbose_name='StatusDat'),
        ),
        migrations.AlterField(
            model_name='table212',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table215',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table215',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table215',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table215',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table215',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table215',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table215',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table217',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table217',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table217',
            name='CoordNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='CoordNo'),
        ),
        migrations.AlterField(
            model_name='table217',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table217',
            name='DocNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocNo'),
        ),
        migrations.AlterField(
            model_name='table217',
            name='DocType',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocType'),
        ),
        migrations.AlterField(
            model_name='table217',
            name='LangNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='LangNo'),
        ),
        migrations.AlterField(
            model_name='table217',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table217',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='AccArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='AccArtNo'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='AccGenArtNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='AccGenArtNo'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='LnkType',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkType'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='LnkVal',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkVal'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='Reserved',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reserved'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table222',
            name='TermNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TermNo'),
        ),
        migrations.AlterField(
            model_name='table228',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table228',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table228',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table228',
            name='CritNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='CritNo'),
        ),
        migrations.AlterField(
            model_name='table228',
            name='CritVal',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CritVal'),
        ),
        migrations.AlterField(
            model_name='table228',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table228',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table228',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table228',
            name='SeqNo1',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo1'),
        ),
        migrations.AlterField(
            model_name='table228',
            name='SortNo1',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo1'),
        ),
        migrations.AlterField(
            model_name='table228',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='Colors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Colors'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='DocName',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='DocName'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='DocNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocNo'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='DocTermNorm',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocTermNorm'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='DocType',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocType'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='DocType1',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocType1'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='Height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='LangNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='LangNo'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='Reserved',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Reserved'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='TermNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='TermNo'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='URL',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='table231',
            name='Width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='table232',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table232',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table232',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table232',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table232',
            name='DocNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocNo'),
        ),
        migrations.AlterField(
            model_name='table232',
            name='DocType',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocType'),
        ),
        migrations.AlterField(
            model_name='table232',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table232',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table232',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='CoordNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='CoordNo'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='DocNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocNo'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='DocType',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocType'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='LangNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='LangNo'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='Type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='X1',
            field=models.IntegerField(blank=True, null=True, verbose_name='X1'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='X2',
            field=models.IntegerField(blank=True, null=True, verbose_name='X2'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='Y1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Y1'),
        ),
        migrations.AlterField(
            model_name='table233',
            name='Y2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Y2'),
        ),
        migrations.AlterField(
            model_name='table400',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table400',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table400',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table400',
            name='GenArtNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='GenArtNo'),
        ),
        migrations.AlterField(
            model_name='table400',
            name='LnkTargetNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo'),
        ),
        migrations.AlterField(
            model_name='table400',
            name='LnkTargetType',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType'),
        ),
        migrations.AlterField(
            model_name='table400',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table400',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='ArtNr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNr'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='FirstPage',
            field=models.IntegerField(blank=True, null=True, verbose_name='FirstPage'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='GenArtNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='GenArtNo'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='InfType',
            field=models.IntegerField(blank=True, null=True, verbose_name='InfType'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='LnkTargetType',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='LnktargetNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnktargetNo'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table401',
            name='TxtModNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='TxtModNo'),
        ),
        migrations.AlterField(
            model_name='table403',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table403',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table403',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table403',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table403',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table403',
            name='GenArtNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='GenArtNo'),
        ),
        migrations.AlterField(
            model_name='table403',
            name='LnkTargetNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo'),
        ),
        migrations.AlterField(
            model_name='table403',
            name='LnkTargetType',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType'),
        ),
        migrations.AlterField(
            model_name='table403',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table403',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table404',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table404',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table404',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table404',
            name='GenArtNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='GenArtNo'),
        ),
        migrations.AlterField(
            model_name='table404',
            name='LnkTargetNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo'),
        ),
        migrations.AlterField(
            model_name='table404',
            name='LnkTargetType',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType'),
        ),
        migrations.AlterField(
            model_name='table404',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table404',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='CritNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='CritNo'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='CritVal',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CritVal'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='FirstPage',
            field=models.IntegerField(blank=True, null=True, verbose_name='FirstPage'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='GenArtNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='GenArtNo'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='LnkTargetNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='LnkTargetType',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='ArtNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CountryCode'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='DeleteFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='DeleteFlag'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='DocNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocNo'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='DocType',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocType'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='Exclude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exclude'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='GenArtNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='GenArtNo'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='LnkTargetNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='LnkTargetType',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='SeqNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table432',
            name='TableNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='TableNo'),
        ),
    ]
