# Generated by Django 4.0.3 on 2022-08-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0002_suppliers200_data_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers200',
            name='full',
            field=models.IntegerField(blank=True, null=True, verbose_name='Full'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='man_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Man No'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='version_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Version Date'),
        ),
        migrations.AlterField(
            model_name='suppliers200',
            name='adr_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Adr Type'),
        ),
        migrations.AlterField(
            model_name='suppliers200',
            name='brand_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brand No'),
        ),
        migrations.AlterField(
            model_name='suppliers200',
            name='country_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='suppliers200',
            name='doc_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Doc No'),
        ),
        migrations.AlterField(
            model_name='suppliers200',
            name='post_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Post Code'),
        ),
    ]
