# Generated by Django 4.0.3 on 2022-08-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0002_alter_article200_supers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critname210',
            old_name='crin_no',
            new_name='crit_no',
        ),
        migrations.RemoveField(
            model_name='crit210',
            name='art_no_id',
        ),
        migrations.RemoveField(
            model_name='crit210',
            name='crit_no_id',
        ),
        migrations.RemoveField(
            model_name='crit210',
            name='crit_val',
        ),
        migrations.AddField(
            model_name='article200',
            name='crit_no_id',
            field=models.ManyToManyField(blank=True, related_name='crit_no_article', to='inTecdoc.crit210'),
        ),
        migrations.AddField(
            model_name='article200',
            name='crit_val',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CritVal'),
        ),
        migrations.AddField(
            model_name='crit210',
            name='crit_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='CritNo'),
        ),
    ]
