# Generated by Django 4.0.3 on 2022-08-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0003_suppliers200_full_suppliers200_man_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers200',
            name='term1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Term1'),
        ),
    ]
