# Generated by Django 4.0.3 on 2022-08-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0004_suppliers200_term1'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers200',
            name='ref_data_version',
            field=models.IntegerField(blank=True, null=True, verbose_name='ref_data_version'),
        ),
    ]
