# Generated by Django 4.0.3 on 2022-08-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0004_delete_critname210_remove_crit210_first_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article200',
            name='crit_no_id',
            field=models.ManyToManyField(blank=True, related_name='CritNo', to='inTecdoc.crit210'),
        ),
    ]
