# Generated by Django 4.0.3 on 2022-08-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0005_alter_article_200_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ref_203',
            name='ArtNoId',
        ),
        migrations.AddField(
            model_name='article_200',
            name='RefNoId',
            field=models.ManyToManyField(blank=True, to='inTecdoc.ref_203'),
        ),
    ]
