# Generated by Django 4.0.3 on 2022-08-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0005_suppliers200_ref_data_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers200',
            name='post_code_cus',
            field=models.IntegerField(blank=True, null=True, verbose_name='post_code_cus'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='post_code_pobox',
            field=models.IntegerField(blank=True, null=True, verbose_name='post_code_pobox'),
        ),
    ]
