# Generated by Django 4.0.3 on 2022-08-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0006_critval210_remove_article200_crit_val_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critval210',
            name='crit_no',
        ),
    ]
