# Generated by Django 4.0.3 on 2022-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0007_remove_article_200_genartnoid_article_200_genartno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_200',
            name='Country',
            field=models.ManyToManyField(blank=True, related_name='CountryArticle_200', to='inTecdoc.country_202'),
        ),
    ]
