# Generated by Django 4.0.3 on 2022-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0007_alter_suppliers200_post_code_pobox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers200',
            name='post_code_cus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='post_code_cus'),
        ),
    ]
