# Generated by Django 4.0.3 on 2022-08-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0008_alter_suppliers200_post_code_cus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article200',
            name='ref_no_id',
        ),
        migrations.AddField(
            model_name='ref203',
            name='art_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.article200', verbose_name='ManNoName'),
        ),
    ]
