# Generated by Django 4.0.3 on 2022-08-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0009_remove_article200_ref_no_id_ref203_art_no_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref203',
            name='art_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.article200', verbose_name='ArtNo'),
        ),
    ]
