# Generated by Django 4.0.3 on 2022-08-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0009_alter_crit210_crit_val_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article200',
            name='crit_no_id',
        ),
        migrations.RemoveField(
            model_name='crit210',
            name='crit_val_id',
        ),
        migrations.AddField(
            model_name='crit210',
            name='art_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.article200', verbose_name='ArtNo'),
        ),
        migrations.AddField(
            model_name='crit210',
            name='crit_val',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CritVal'),
        ),
        migrations.DeleteModel(
            name='CritVal210',
        ),
    ]
