# Generated by Django 4.0.3 on 2022-08-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0010_alter_ref203_art_no_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref203',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.country202', verbose_name='ManNoName'),
        ),
    ]
