# Generated by Django 4.0.3 on 2022-08-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0011_critval210_remove_crit210_art_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crit210',
            name='art_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.article200', verbose_name='ArtNo'),
        ),
        migrations.AlterField(
            model_name='crit210',
            name='crit_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.critval210', verbose_name='CritNo'),
        ),
    ]
