# Generated by Django 4.0.3 on 2022-08-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0011_ref203_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='table404',
            name='sort_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='sort_no'),
        ),
        migrations.AddField(
            model_name='table410',
            name='sort_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='sort_no'),
        ),
    ]
