# Generated by Django 4.0.3 on 2022-08-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0012_alter_crit210_art_no_id_alter_crit210_crit_no_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ref203',
            old_name='ref_no',
            new_name='ref_name',
        ),
    ]
