# Generated by Django 4.0.3 on 2022-08-26 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0012_table404_sort_no_table410_sort_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref203',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.country202', verbose_name='country_code'),
        ),
    ]
