# Generated by Django 4.0.3 on 2022-08-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0013_rename_ref_no_ref203_ref_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ref203',
            old_name='ref_name',
            new_name='ref_no',
        ),
    ]
