# Generated by Django 4.0.3 on 2022-08-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0014_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='body_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BODY_TYPE'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='ccm_tech',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CCM_TECH'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='cylinders',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CYLINDERS'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='drive_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DRIVE_TYPE'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='engine_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ENGINE_CODE'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='engine_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ENGINE_TYPE'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='fuel_mixture_formation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FUEL_MIXTURE_FORMATION'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FUEL_TYPE'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='hp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HP'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='kw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='KW'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='litres',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LITRES'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='values_per_chamber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VALVES_PER_CHAMBER'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='veh_brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VEH_BRAND'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='veh_model_intl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VEH_MODEL_INTL'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='veh_model_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='VEH_MODEL_NO'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='veh_type_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VEH_TYPE_NAME'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='veh_type_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='VEH_TYPE_NO'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='YEAR'),
        ),
    ]
