# Generated by Django 4.0.3 on 2022-08-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0016_alter_ref203_man_no_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ref203',
            name='sort_no',
        ),
    ]
