# Generated by Django 4.1.1 on 2022-09-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0017_alter_article200_art_stat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_from', models.BigIntegerField(blank=True, null=True)),
                ('page_to', models.BigIntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
