# Generated by Django 4.0.3 on 2022-08-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0017_remove_ref203_sort_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers200',
            name='adr_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='AdrType'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='country_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CountryCode'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='doc_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocNo'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='doc_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocType'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='post_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PostCode'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='street_two',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street2'),
        ),
        migrations.AddField(
            model_name='suppliers200',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Web'),
        ),
    ]
