# Generated by Django 4.0.3 on 2022-08-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0018_suppliers200_adr_type_suppliers200_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table410',
            name='art_no_id',
        ),
        migrations.RemoveField(
            model_name='table410',
            name='first_page',
        ),
        migrations.RemoveField(
            model_name='table410',
            name='lnk_target_type',
        ),
        migrations.RemoveField(
            model_name='table410',
            name='seq_no',
        ),
        migrations.RemoveField(
            model_name='table410',
            name='sort_no',
        ),
        migrations.AddField(
            model_name='lnk400',
            name='first_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='FirstPage'),
        ),
        migrations.AddField(
            model_name='lnk400',
            name='sort_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='lnk_target_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.lnk400'),
        ),
        migrations.DeleteModel(
            name='Table404',
        ),
    ]
