# Generated by Django 4.1.1 on 2022-09-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0019_remove_article200_supers_id_supers204_art_no_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ref203',
            old_name='country_code',
            new_name='country_code_id',
        ),
    ]
