# Generated by Django 4.0.3 on 2022-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0019_remove_table410_art_no_id_remove_table410_first_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnk400',
            name='art_no',
        ),
        migrations.AddField(
            model_name='lnk400',
            name='art_no',
            field=models.ManyToManyField(blank=True, related_name='ArtNoLnk', to='inTecdoc.article200'),
        ),
    ]
