# Generated by Django 4.1.1 on 2022-09-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0020_rename_country_code_ref203_country_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crit210',
            name='crit_no_id',
            field=models.ForeignKey(blank=True, default='нет критерия', null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.critval210', verbose_name='CritNo'),
        ),
    ]
