# Generated by Django 4.0.3 on 2022-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0020_remove_lnk400_art_no_lnk400_art_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lnk400',
            new_name='Lnk400and404',
        ),
        migrations.RemoveField(
            model_name='doc231and232',
            name='art_no_id',
        ),
        migrations.RemoveField(
            model_name='doc231and232',
            name='doc_type',
        ),
        migrations.AddField(
            model_name='article200',
            name='doc_no',
            field=models.ManyToManyField(blank=True, related_name='doc_no_article', to='inTecdoc.doc231and232'),
        ),
    ]
