# Generated by Django 4.0.3 on 2022-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0021_rename_lnk400_lnk400and404_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade207',
            name='sort_no',
        ),
        migrations.AddField(
            model_name='doc231and232',
            name='doc_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocTermNorm'),
        ),
    ]
