# Generated by Django 4.1.1 on 2022-09-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0021_alter_crit210_crit_no_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crit210',
            name='crit_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inTecdoc.critval210', verbose_name='CritNo'),
        ),
        migrations.AlterField(
            model_name='critval210',
            name='crit_no',
            field=models.BigIntegerField(blank=True, default='нет критерия', null=True, verbose_name='CritNo'),
        ),
    ]
