# Generated by Django 4.0.3 on 2022-08-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0022_remove_trade207_sort_no_doc231and232_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lnk400',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_art_no', models.IntegerField(blank=True, null=True, verbose_name='GenArtNo')),
                ('lnk_target_type', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType')),
                ('lnk_target_no', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo')),
                ('seq_no', models.IntegerField(blank=True, null=True, verbose_name='SeqNo')),
                ('art_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArtNoLnk400', to='inTecdoc.article200')),
            ],
        ),
        migrations.CreateModel(
            name='Table404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_art_no', models.IntegerField(blank=True, null=True, verbose_name='GenArtNo')),
                ('lnk_target_type', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType')),
                ('lnk_target_no', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo')),
                ('art_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArtNoTable404', to='inTecdoc.article200')),
            ],
        ),
        migrations.AddField(
            model_name='table410',
            name='art_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArtNoTable410', to='inTecdoc.article200'),
        ),
        migrations.AddField(
            model_name='table410',
            name='first_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='FirstPage'),
        ),
        migrations.AddField(
            model_name='table410',
            name='gen_art_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='GenArtNo'),
        ),
        migrations.AddField(
            model_name='table410',
            name='lnk_target_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType'),
        ),
        migrations.AddField(
            model_name='table410',
            name='seq_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='SeqNo'),
        ),
        migrations.AlterField(
            model_name='table410',
            name='lnk_target_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo'),
        ),
        migrations.DeleteModel(
            name='Lnk400and404',
        ),
    ]
