# Generated by Django 4.1.1 on 2022-09-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0022_alter_crit210_crit_no_id_alter_critval210_crit_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critval210',
            name='crit_no',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='CritNo'),
        ),
    ]
