# Generated by Django 4.1.1 on 2022-09-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0023_alter_critval210_crit_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article200',
            options={},
        ),
        migrations.AlterModelOptions(
            name='crit210',
            options={},
        ),
        migrations.AlterModelOptions(
            name='critval210',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doc231and232',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manufacture203',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ref203',
            options={},
        ),
        migrations.AlterModelOptions(
            name='suppliers200',
            options={},
        ),
    ]
