# Generated by Django 4.0.3 on 2022-08-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0023_lnk400_table404_table410_art_no_table410_first_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article200',
            old_name='country',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='article200',
            old_name='doc_no',
            new_name='doc_no_id',
        ),
        migrations.RenameField(
            model_name='lnk400',
            old_name='art_no',
            new_name='art_no_id',
        ),
        migrations.RenameField(
            model_name='table404',
            old_name='art_no',
            new_name='art_no_id',
        ),
        migrations.RenameField(
            model_name='table410',
            old_name='art_no',
            new_name='art_no_id',
        ),
    ]
