# Generated by Django 4.1.1 on 2022-09-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0024_alter_article200_options_alter_crit210_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc231and232',
            name='file_paths',
            field=models.FilePathField(blank=True, null=True, path=models.FilePathField(blank=True, max_length=255, null=True, verbose_name='DocName')),
        ),
        migrations.AlterField(
            model_name='doc231and232',
            name='doc_name',
            field=models.FilePathField(blank=True, max_length=255, null=True, verbose_name='DocName'),
        ),
    ]
