# Generated by Django 4.0.3 on 2022-08-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0025_alter_article200_options_alter_country202_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critval210',
            options={'verbose_name': 'Список критерий', 'verbose_name_plural': 'Список критерий'},
        ),
    ]
