# Generated by Django 4.0.3 on 2022-08-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0026_alter_critval210_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ref203',
            options={'verbose_name': 'Производитель авто', 'verbose_name_plural': 'Производители авто'},
        ),
    ]
