# Generated by Django 4.0.3 on 2022-08-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0027_alter_ref203_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacture203',
            options={'verbose_name': 'Список: производитель авто', 'verbose_name_plural': 'Список производителей авто'},
        ),
    ]
