# Generated by Django 4.1.1 on 2022-09-15 09:20

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0029_alter_doc231and232_file_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc231and232',
            name='file_paths',
            field=models.FilePathField(blank=True, null=True, path=pathlib.PureWindowsPath('C:/Users/Sirius_McLine/PycharmProjects/BrixoDoc/ImportTAF/sources_tec/image')),
        ),
    ]
