# Generated by Django 4.0.3 on 2022-08-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0029_alter_manufacture203_options_alter_ref203_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacture203',
            options={'verbose_name': 'Производитель авто', 'verbose_name_plural': 'Производители авто'},
        ),
    ]
