# Generated by Django 4.0.3 on 2022-08-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0030_alter_manufacture203_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supers204',
            name='sort_no',
        ),
    ]
