# Generated by Django 4.0.3 on 2022-08-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0031_remove_supers204_sort_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country202',
            options={'default_related_name': 'country', 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
    ]
