# Generated by Django 4.0.3 on 2022-08-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0032_alter_country202_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country202',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
    ]
