# Generated by Django 4.1.1 on 2022-09-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0033_alter_doc231and232_file_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc231and232',
            name='file_paths',
        ),
    ]
