# Generated by Django 4.0.3 on 2022-08-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0034_alter_country202_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc231and232',
            name='doc_content_type',
        ),
        migrations.AddField(
            model_name='doc231and232',
            name='doc_type_one',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocTermNorm'),
        ),
        migrations.AlterField(
            model_name='doc231and232',
            name='doc_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocContentType'),
        ),
    ]
