# Generated by Django 4.0.3 on 2022-08-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0035_remove_doc231and232_doc_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc231and232',
            name='doc_type_one',
        ),
    ]
