# Generated by Django 4.1.1 on 2022-09-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0035_doc231and232_file_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc231and232',
            name='file_field',
        ),
        migrations.AddField(
            model_name='doc231and232',
            name='file_paths',
            field=models.FilePathField(blank=True, null=True, path='C:\\Users\\Sirius_McLine\\PycharmProjects\\BrixoDoc/ImportTAF/sources_tec/image/'),
        ),
    ]
