# Generated by Django 4.0.3 on 2022-08-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inTecdoc', '0036_remove_doc231and232_doc_type_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc231and232',
            name='doc_type_one',
            field=models.IntegerField(blank=True, null=True, verbose_name='DocTermNorm'),
        ),
    ]
