# Generated by Django 4.0.3 on 2022-03-18 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExternalId', models.TextField(verbose_name='ExternalId')),
                ('AssemblyGroup', models.TextField(verbose_name='AssemblyGroup')),
                ('GenericArticle', models.TextField(verbose_name='GenericArticle')),
                ('ArticleNumber', models.CharField(max_length=255, verbose_name='ArticleNumber')),
                ('Type', models.IntegerField(verbose_name='Type')),
                ('GenericArticleNumber', models.TextField(verbose_name='GenericArticleNumber')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(verbose_name='Name')),
                ('ModelNumber', models.IntegerField(verbose_name='ModelNumber')),
                ('VehicleBrandId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VehicleModels', to='SiteBrixo.vehiclebrands')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeNumber', models.IntegerField(verbose_name='TypeNumber')),
                ('Year', models.TextField(verbose_name='Year')),
                ('BodyType', models.TextField(verbose_name='BodyType')),
                ('DriveType', models.TextField(verbose_name='DriveType')),
                ('EngineType', models.TextField(verbose_name='EngineType')),
                ('ValvesPerChamber', models.IntegerField(verbose_name='ValvesPerChamber')),
                ('Cylinders', models.IntegerField(verbose_name='Cylinders')),
                ('Volume', models.IntegerField(verbose_name='Volume')),
                ('CcmTech', models.IntegerField(verbose_name='CcmTech')),
                ('FuelType', models.TextField(verbose_name='FuelType')),
                ('FuelMixtureFormation', models.TextField(verbose_name='FuelMixtureFormation')),
                ('HorsePowers', models.TextField(verbose_name='HorsePowers')),
                ('KiloWatts', models.TextField(verbose_name='KiloWatts')),
                ('Engines', models.TextField(verbose_name='Engines')),
                ('TypeName', models.TextField(verbose_name='TypeName')),
                ('VehicleModelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicles', to='SiteBrixo.vehiclemodels')),
            ],
        ),
        migrations.CreateModel(
            name='Marketplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField(verbose_name='Type')),
                ('OzonId', models.IntegerField(verbose_name='OzonId')),
                ('ArticleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Marketplaces', to='SiteBrixo.articles')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Path', models.TextField(verbose_name='Path')),
                ('Order', models.IntegerField(verbose_name='Order')),
                ('ArticleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='File', to='SiteBrixo.articles')),
                ('VehicleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='File', to='SiteBrixo.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesToVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criterias', models.TextField(verbose_name='Criterias')),
                ('ExternalId', models.TextField(verbose_name='ExternalId')),
                ('ArticleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticlesToVehicle', to='SiteBrixo.articles')),
                ('VehicleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticlesToVehicle', to='SiteBrixo.vehicles')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='SupplierId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Articles', to='SiteBrixo.suppliers'),
        ),
        migrations.CreateModel(
            name='ArticleOem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.TextField(verbose_name='Brand')),
                ('OemNumber', models.TextField(verbose_name='OemNumber')),
                ('IsOriginal', models.IntegerField(verbose_name='IsOriginal')),
                ('NormalizerOemNumber', models.CharField(max_length=255, verbose_name='NormalizerOemNumber')),
                ('IsReplacer', models.IntegerField(verbose_name='IsReplacer')),
                ('ArticleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticleOem', to='SiteBrixo.articles')),
            ],
        ),
    ]
