# Generated by Django 4.0.3 on 2022-04-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleoem',
            name='ArticleId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArticleOem', to='SiteBrixo.articles'),
        ),
        migrations.AlterField(
            model_name='articleoem',
            name='Brand',
            field=models.TextField(blank=True, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='articleoem',
            name='IsOriginal',
            field=models.IntegerField(blank=True, null=True, verbose_name='IsOriginal'),
        ),
        migrations.AlterField(
            model_name='articleoem',
            name='IsReplacer',
            field=models.IntegerField(blank=True, null=True, verbose_name='IsReplacer'),
        ),
        migrations.AlterField(
            model_name='articleoem',
            name='NormalizerOemNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NormalizerOemNumber'),
        ),
        migrations.AlterField(
            model_name='articleoem',
            name='OemNumber',
            field=models.TextField(blank=True, null=True, verbose_name='OemNumber'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ArticleNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ArticleNumber'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='AssemblyGroup',
            field=models.TextField(blank=True, null=True, verbose_name='AssemblyGroup'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ExternalId',
            field=models.TextField(blank=True, null=True, verbose_name='ExternalId'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='GenericArticle',
            field=models.TextField(blank=True, null=True, verbose_name='GenericArticle'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='GenericArticleNumber',
            field=models.TextField(blank=True, null=True, verbose_name='GenericArticleNumber'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='SupplierId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Articles', to='SiteBrixo.suppliers'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='articlestovehicle',
            name='ArticleId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArticlesToVehicle', to='SiteBrixo.articles'),
        ),
        migrations.AlterField(
            model_name='articlestovehicle',
            name='Criterias',
            field=models.TextField(blank=True, null=True, verbose_name='Criterias'),
        ),
        migrations.AlterField(
            model_name='articlestovehicle',
            name='ExternalId',
            field=models.TextField(blank=True, null=True, verbose_name='ExternalId'),
        ),
        migrations.AlterField(
            model_name='articlestovehicle',
            name='VehicleId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArticlesToVehicle', to='SiteBrixo.vehicles'),
        ),
        migrations.AlterField(
            model_name='file',
            name='ArticleId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File', to='SiteBrixo.articles'),
        ),
        migrations.AlterField(
            model_name='file',
            name='Order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='file',
            name='Path',
            field=models.TextField(blank=True, null=True, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='VehicleId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File', to='SiteBrixo.vehicles'),
        ),
        migrations.AlterField(
            model_name='marketplaces',
            name='ArticleId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Marketplaces', to='SiteBrixo.articles'),
        ),
        migrations.AlterField(
            model_name='marketplaces',
            name='OzonId',
            field=models.IntegerField(blank=True, null=True, verbose_name='OzonId'),
        ),
        migrations.AlterField(
            model_name='marketplaces',
            name='Type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='Name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vehiclebrands',
            name='Name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vehiclemodels',
            name='ModelNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='ModelNumber'),
        ),
        migrations.AlterField(
            model_name='vehiclemodels',
            name='Name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vehiclemodels',
            name='VehicleBrandId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VehicleModels', to='SiteBrixo.vehiclebrands'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='BodyType',
            field=models.TextField(blank=True, null=True, verbose_name='BodyType'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='CcmTech',
            field=models.IntegerField(blank=True, null=True, verbose_name='CcmTech'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Cylinders',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cylinders'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='DriveType',
            field=models.TextField(blank=True, null=True, verbose_name='DriveType'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='EngineType',
            field=models.TextField(blank=True, null=True, verbose_name='EngineType'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Engines',
            field=models.TextField(blank=True, null=True, verbose_name='Engines'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='FuelMixtureFormation',
            field=models.TextField(blank=True, null=True, verbose_name='FuelMixtureFormation'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='FuelType',
            field=models.TextField(blank=True, null=True, verbose_name='FuelType'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='HorsePowers',
            field=models.TextField(blank=True, null=True, verbose_name='HorsePowers'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='KiloWatts',
            field=models.TextField(blank=True, null=True, verbose_name='KiloWatts'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='TypeName',
            field=models.TextField(blank=True, null=True, verbose_name='TypeName'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='TypeNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='TypeNumber'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='ValvesPerChamber',
            field=models.IntegerField(blank=True, null=True, verbose_name='ValvesPerChamber'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='VehicleModelId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicles', to='SiteBrixo.vehiclemodels'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Year',
            field=models.TextField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
