# Generated by Django 4.0.3 on 2022-04-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0002_alter_articleoem_articleid_alter_articleoem_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='Attributes',
            field=models.TextField(blank=True, null=True, verbose_name='Attributes'),
        ),
    ]
