# Generated by Django 4.0.3 on 2022-04-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0003_articles_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Order',
            field=models.TextField(blank=True, null=True, verbose_name='Order'),
        ),
    ]
