# Generated by Django 4.0.3 on 2022-04-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0004_alter_file_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayBra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bra_brand_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='bra_brand_no')),
                ('bra_short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='bra_short_name')),
                ('view_term_plain', models.CharField(blank=True, max_length=255, null=True, verbose_name='view_term_plain')),
            ],
        ),
    ]
