# Generated by Django 4.0.4 on 2022-05-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0005_displaybra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclebrands',
            options={'default_related_name': 'VehicleBrands'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodels',
            options={'default_related_name': 'VehicleModels'},
        ),
    ]
