# Generated by Django 4.0.4 on 2022-05-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0006_alter_vehiclebrands_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemodels',
            options={},
        ),
        migrations.AlterField(
            model_name='vehiclemodels',
            name='VehicleBrandId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SiteBrixo.vehiclebrands'),
        ),
    ]
