# Generated by Django 4.0.3 on 2022-07-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0008_alter_vehiclemodels_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleoem',
            name='Brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='articleoem',
            name='OemNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OemNumber'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='AssemblyGroup',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AssemblyGroup'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Attributes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Attributes'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ExternalId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ExternalId'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='GenericArticle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GenericArticle'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='GenericArticleNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GenericArticleNumber'),
        ),
        migrations.AlterField(
            model_name='articlestovehicle',
            name='Criterias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Criterias'),
        ),
        migrations.AlterField(
            model_name='articlestovehicle',
            name='ExternalId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ExternalId'),
        ),
        migrations.AlterField(
            model_name='file',
            name='Order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='file',
            name='Path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vehiclebrands',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vehiclemodels',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='BodyType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BodyType'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='DriveType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DriveType'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='EngineType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EngineType'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Engines',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Engines'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='FuelMixtureFormation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FuelMixtureFormation'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='FuelType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FuelType'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='HorsePowers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HorsePowers'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='KiloWatts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='KiloWatts'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='TypeName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TypeName'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='Year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Year'),
        ),
    ]
