# Generated by Django 4.0.3 on 2022-07-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0009_alter_articleoem_brand_alter_articleoem_oemnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Attributes',
            field=models.JSONField(blank=True, null=True, verbose_name='Attributes'),
        ),
    ]
