# Generated by Django 4.0.3 on 2022-07-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0010_alter_articles_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CountryCode'),
        ),
        migrations.AddField(
            model_name='vehiclebrands',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AddField(
            model_name='vehiclebrands',
            name='ManNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='ManNo'),
        ),
        migrations.AddField(
            model_name='vehiclebrands',
            name='RefDataVersion',
            field=models.IntegerField(blank=True, null=True, verbose_name='RefDataVersion'),
        ),
        migrations.AddField(
            model_name='vehiclebrands',
            name='VersionDate',
            field=models.IntegerField(blank=True, null=True, verbose_name='VersionDate'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryCode', models.CharField(blank=True, max_length=255, null=True, verbose_name='CountryCode')),
                ('Article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Articles', to='SiteBrixo.articles')),
            ],
        ),
    ]
