# Generated by Django 4.0.3 on 2022-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0011_articles_countrycode_vehiclebrands_brandno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='CountryCode',
        ),
        migrations.RemoveField(
            model_name='vehiclebrands',
            name='BrandNo',
        ),
        migrations.RemoveField(
            model_name='vehiclebrands',
            name='ManNo',
        ),
        migrations.RemoveField(
            model_name='vehiclebrands',
            name='RefDataVersion',
        ),
        migrations.RemoveField(
            model_name='vehiclebrands',
            name='VersionDate',
        ),
        migrations.AddField(
            model_name='articles',
            name='BrandNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='BrandNo'),
        ),
        migrations.AddField(
            model_name='articles',
            name='ManNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='ManNo'),
        ),
        migrations.AddField(
            model_name='articles',
            name='RefDataVersion',
            field=models.IntegerField(blank=True, null=True, verbose_name='RefDataVersion'),
        ),
        migrations.AddField(
            model_name='articles',
            name='VersionDate',
            field=models.IntegerField(blank=True, null=True, verbose_name='VersionDate'),
        ),
    ]
