# Generated by Django 4.0.3 on 2022-07-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0012_remove_articles_countrycode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='ManNo',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='RefDataVersion',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='VersionDate',
        ),
    ]
