# Generated by Django 4.0.3 on 2022-07-29 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteBrixo', '0013_remove_articles_manno_remove_articles_refdataversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleoem',
            name='ManNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='ManNo'),
        ),
        migrations.AddField(
            model_name='articleoem',
            name='SortNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='SortNo'),
        ),
        migrations.AddField(
            model_name='articles',
            name='GenArtNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='GenArtNo'),
        ),
        migrations.AddField(
            model_name='articles',
            name='Gtin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gtin'),
        ),
        migrations.AddField(
            model_name='articles',
            name='StatusDat',
            field=models.IntegerField(blank=True, null=True, verbose_name='StatusDat'),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradeNo', models.CharField(blank=True, max_length=255, null=True, verbose_name='TradeNo')),
                ('FirstPage', models.IntegerField(blank=True, null=True, verbose_name='FirstPage')),
                ('SortNo', models.IntegerField(blank=True, null=True, verbose_name='SortNo')),
                ('Article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Articl', to='SiteBrixo.articles')),
            ],
        ),
        migrations.CreateModel(
            name='Supers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupersNo', models.CharField(blank=True, max_length=255, null=True, verbose_name='CountryCode')),
                ('SortNo', models.IntegerField(blank=True, null=True, verbose_name='SortNo')),
                ('Article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='SiteBrixo.articles')),
            ],
        ),
        migrations.CreateModel(
            name='LnkTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LnkTargetType', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetType')),
                ('LnkTargetNo', models.IntegerField(blank=True, null=True, verbose_name='LnkTargetNo')),
                ('SeqNo', models.IntegerField(blank=True, null=True, verbose_name='SeqNo')),
                ('Article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Art', to='SiteBrixo.articles')),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocNo', models.IntegerField(blank=True, null=True, verbose_name='DocNo')),
                ('LangNo', models.IntegerField(blank=True, null=True, verbose_name='LangNo')),
                ('DocName', models.CharField(blank=True, max_length=255, null=True, verbose_name='DocName')),
                ('DocContentType', models.IntegerField(blank=True, null=True, verbose_name='DocContentType')),
                ('DocTermNorm', models.IntegerField(blank=True, null=True, verbose_name='DocTermNorm')),
                ('DocType', models.IntegerField(blank=True, null=True, verbose_name='DocType')),
                ('Article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Arti', to='SiteBrixo.articles')),
            ],
        ),
        migrations.CreateModel(
            name='Crit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CritNo', models.IntegerField(blank=True, null=True, verbose_name='CritNo')),
                ('CritVal', models.CharField(blank=True, max_length=255, null=True, verbose_name='CritVal')),
                ('FirstPage', models.IntegerField(blank=True, null=True, verbose_name='FirstPage')),
                ('Article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Artic', to='SiteBrixo.articles')),
            ],
        ),
    ]
